export default [
  'Entretenimento',
  'Educação',
  'Estilo de Vida',
  'Saúde e Bem-Estar',
  'Música',
  'Ciência e Tecnologia',
  'Vlogs',
  'Notícias e Política',
  'Automóveis',
  'Animais de Estimação',
  'Humor',
  'Negócios e Finanças',
  'Alimentação',
  'Arte e Cultura',
  'Viagem',
  'Família e Relacionamentos',
  'Literatura',
  'Desenvolvimento Pessoal',
  'Esportes',
];
